models:
  #folder: '/home/chris/code2/hb_models'
  folder: '/home/cmeier/code/hb_models'

datasets:
  kasteren:
    #sens_file_path: '/home/chris/code2/datasets/kasteren/kasterenSenseData.txt'
    #act_file_path: '/home/chris/code2/datasets/kasteren/kasterenActData.txt'
    sens_file_path: '/home/cmeier/code/datasets/kasteren/kasterenSenseData.txt'
    act_file_path: '/home/cmeier/code/datasets/kasteren/kasterenActData.txt'

  pendigits:
    #test_file_path: '/home/chris/code2/datasets/pendigits/pendigits-orig.tes'
    #train_file_path: '/home/chris/code2/datasets/pendigits/pendigits-orig.tra'
    test_file_path: '/home/cmeier/code/datasets/pendigits/pendigits-orig.tes'
    train_file_path: '/home/cmeier/code/datasets/pendigits/pendigits-orig.tra'
  homeassistant:
    database_path: '/home/cmeier/code/datasets/homeassistant/home-assistant_v2.db'
    #database_path: '/home/cmeier/code/datasets/homeassistant/simon_hass_v2.db'
    #database_path: '/home/cmeier/code/datasets/homeassistant/github_ha_v2.db'
    act_file_path: '/home/cmeier/code/datasets/homeassistant/activities.csv'
    labels_path: '/home/cmeier/code/datasets/homeassistant/labels.yaml'
