version: "3"
services:
  datascience-notebook:
      build: .
      volumes:
        - /home/chris/code2/hassbrain_jupyter/data:/home/jovyan/work
      ports:
        - 8888:8888
      container_name: hassbrain_notebook

