models:
  folder: '/home/chris/code2/hassbrain_algorithm/hb_models'

datasets:
  kasteren:
    sens_file_path: '/home/chris/code2/hassbrain_algorithm/datasets/kasteren/kasterenSenseData.txt'
    act_file_path: '/home/chris/code2/hassbrain_algorithm/datasets/kasteren/kasterenActData.txt'

  pendigits:
    test_file_path: '/home/chris/code2/hassbrain_algorithm/datasets/pendigits/pendigits-orig.tes'
    train_file_path: '/home/chris/code2/hassbrain_algorithm/datasets/pendigits/pendigits-orig.tra'
