datasets:
  kasteren:
    sens_file_path: '/home/chris/code2/hassbrain_algorithm/datasets/kasteren/kasterenSenseData.txt'
    act_file_path: '/home/chris/code2/hassbrain_algorithm/datasets/kasteren/kasterenActData.txt'

  pen_digit:
    test_file_path: ''
    train_file_path: ''

